### ISSUE TITLE
Missing presentation slides for SyGuS-Comp 2017

### ISSUE THREAD

**Issue by 4tXJ7f** [SyGuS-Org/sygus-org.github.io#1]
The new website is looking great! However, I've noticed that the slides for the final presentations of CVC4 and DryadSynth are missing for SyGuS-Comp 2017. I am getting a 404 error when trying to access the files. Nothing urgent, just figured I'd leave a note.

**Comment by SaswatPadhi** [comment]
Thanks Andres 🙂

The presentation files were in the repo, but there was a small typo in the links pointing to them. I just pushed a fix.
